// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprdAIbX2pwPnnnYjQE6DS_SQ18lJLMXA',
    appId: '1:1073556131048:web:32a7ce71d2440d18978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    authDomain: 'finflow-3df94.firebaseapp.com',
    storageBucket: 'finflow-3df94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgrCwkjDCWz5JDfbcdAhaV0z_iN618j7U',
    appId: '1:1073556131048:android:ac894c764d93be3f978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    storageBucket: 'finflow-3df94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBOqvBjnvpg7ZTQfxEl8GTjgjkBv5c0M',
    appId: '1:1073556131048:ios:923e853ab61d5ebd978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    storageBucket: 'finflow-3df94.appspot.com',
    iosClientId: '1073556131048-qbkvdqltan439u857cli81b1td6vdflq.apps.googleusercontent.com',
    iosBundleId: 'com.example.finflowIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBOqvBjnvpg7ZTQfxEl8GTjgjkBv5c0M',
    appId: '1:1073556131048:ios:98de8e1debb64692978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    storageBucket: 'finflow-3df94.appspot.com',
    iosClientId: '1073556131048-hgs4ejkf5326clm8va5q2cmts26gpskk.apps.googleusercontent.com',
    iosBundleId: 'com.example.finflowIot.RunnerTests',
  );
}
