// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Px0gHrMfvSHTGIr2NKjN8vihTwf7ML8',
    appId: '1:1073556131048:web:32a7ce71d2440d18978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    authDomain: 'finflow-3df94.firebaseapp.com',
    databaseURL: 'https://finflow-3df94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finflow-3df94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnwIjxhVpCVUnt6V6OJ67y4c2Aoi6ixp8',
    appId: '1:1073556131048:android:ac894c764d93be3f978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    databaseURL: 'https://finflow-3df94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finflow-3df94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xSwLXYMtZ7T-rTiFc5cxLZ2H-Os9HkE',
    appId: '1:1073556131048:ios:923e853ab61d5ebd978d5d',
    messagingSenderId: '1073556131048',
    projectId: 'finflow-3df94',
    databaseURL: 'https://finflow-3df94-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finflow-3df94.appspot.com',
    androidClientId: '1073556131048-l1dk16dsani6jeckdo8mhvudlts73u4a.apps.googleusercontent.com',
    iosClientId: '1073556131048-qbkvdqltan439u857cli81b1td6vdflq.apps.googleusercontent.com',
    iosBundleId: 'com.example.finflowIot',
  );
}
